name: Deployment pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run tsc
      - name: test
        run: npm run test
      - name: debloy
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip')}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'sheltered-beyond-58641'
          heroku_email: 'ville.l.alatalo@gmail.com'
          healthcheck: 'https://sheltered-beyond-58641.herokuapp.com/health'
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true
